Path: news.astraweb.com!border6.newsrouter.astraweb.com!news.astraweb.com!border2.newsrouter.astraweb.com!peer01.iad.highwinds-media.com!news.highwinds-media.com!feed-me.highwinds-media.com!post01.iad.highwinds-media.com!fx23.iad.POSTED!not-for-mail
From: Spyder McGurk <Smcgurk@veration.edu>
Newsgroups: alt.binaries.e-book
Subject: Re: ATTN: Psychopath - "agent (Medium).jpg" 213.1 kBytes yEnc
Message-ID: <5nl7kahf6idkev93a8qu5k9m4095nt5p2i@4ax.com>
References: <rei7ka1vo93moj2kh7mpn3iion6v5tebtv@4ax.com>
X-Newsreader: Forte Agent 6.00/32.1186
X-No-Archive: yes
Lines: 1750
X-Complaints-To: abuse@easynews.com
Organization: Easynews - www.easynews.com
Bytes: 226506
X-Complaints-Info: Please be sure to forward a copy of ALL headers otherwise we will be unable to process your complaint properly.
Date: Fri, 01 May 2015 14:43:53 -0500
X-Received-Bytes: 226569
X-Received-Body-CRC: 1037710279

On Fri, 01 May 2015 13:46:10 -0500, Highlander <nobody@yahoo.com>
wrote:

>Now, the names of the books and authors are too long for the window in
>the newsreader and each has to be selected to see the full info.  I
>know you are just trying to please the masses and some folks are not
>real savy with the whole newsgroups thing.  At any rate, just my 2
>cents and thanks again for your efforts!

I'm using the same news reader you are and I don't have a problem. Are
you using the 3 pane view? If you are try switching to a single pane
view.

This is the way it looks to me.

Crap at the end of the string
