Path: news.astraweb.com
From: Spyder McGurk <Smcgurk@veration.edu>
Newsgroups: alt.binaries.e-book
Subject: Re: ATTN: Psychopath - "agent (Medium).jpg" 213.1 kBytes yEnc
Message-ID: <5nl7kahf6idkev93a8qu5k9m4095nt5p2i@4ax.com>
References: <rei7ka1vo93moj2kh7mpn3iion6v5tebtv@4ax.com>
X-Newsreader: Forte Agent 6.00/32.1186
X-No-Archive: yes
Lines: 1750
X-Complaints-To: abuse@easynews.com
Organization: Easynews - www.easynews.com
Bytes: 226506
X-Complaints-Info: Please be sure to forward a copy of ALL headers otherwise we will be unable to process your complaint properly.
Date: Fri, 01 May 2015 14:43:53 -0500
X-Received-Bytes: 226569
X-Received-Body-CRC: 1037710279

First Line
Second Line
This is a test message to which we're more focused on the headers then anything
In this message, we write some content here, but the key is that we shouldn't
pick the header up below this text which would otherwise flag an invalid header
entry later on.

X-DMCA: True

