Path: news.astraweb.com!border6.newsrouter.astraweb.com!news.alt.net!border3.nntp.dca.giganews.com!backlog3.nntp.dca3.giganews.com!border1.nntp.dca.giganews.com!border1.nntp.dca1.giganews.com!border2.nntp.dca1.giganews.com!nntp.giganews.com!peer01.iad.highwinds-media.com!feed-me.highwinds-media.com!peer02.fr7!news.highwinds-media.com!post02.fr7!fx09.am4.POSTED!not-for-mail
From: empty@message.ru
Newsgroups: alt.binaries.empty
Subject: Empty Message
Message-ID: <abcdefg.hijk@lmno.pqr.ru>
Organization: <no organization>
Lines: 1
NNTP-Posting-Host: None
X-Complaints-To: abuse@pqr.ru
NNTP-Posting-Date: Wed,  9 Sep 2015 00:00:00 UTC
Date: Wed, 9 Sep 2015 00:00:00 -0000


